### ISSUE TITLE
performance.scenarios (The system cannot find the file specified)

### ISSUE THREAD

**Issue by mironoff2007** [androidbroadcast/AndroidDevBenchmark#1]
Gradle User Home: C:\Users\MSI_B5M\StudioProjects\AndroidDevBenchmark\gradle-user-home
Targets: [clean_build]
com.typesafe.config.ConfigException$IO: C:\Users\MSI_B5M\StudioProjects\AndroidDevBenchmark\performance.scenarios: java.io.FileNotFoundException: C:\Users\MSI_B5M\StudioProjects\AndroidDevBenchmark\performance.scenarios (The system cannot find the file specified)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:188)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
        at com.typesafe.config.impl.Parseable.parse(Parseable.java:299)
        at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:689)
        at org.gradle.profiler.ScenarioLoader.loadScenarios(ScenarioLoader.java:209)
        at org.gradle.profiler.ScenarioLoader.doLoadScenarios(ScenarioLoader.java:175)
        at org.gradle.profiler.ScenarioLoader.loadScenarios(ScenarioLoader.java:156)
        at org.gradle.profiler.Main.run(Main.java:56)
        at org.gradle.profiler.Main.main(Main.java:25)
Caused by: java.io.FileNotFoundException: C:\Users\MSI_B5M\StudioProjects\AndroidDevBenchmark\performance.scenarios (The system cannot find the file specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at com.typesafe.config.impl.Parseable$ParseableFile.reader(Parseable.java:638)
        at com.typesafe.config.impl.Parseable.reader(Parseable.java:99)
        at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:231)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
        ... 8 more

**Comment by mironoff2007** [comment]
Надо каждый проект отдельно запускать. Я запустил из корня репозитория
